### PR TITLE
Add deployment documentation to readme

### PR DESCRIPTION
**Pull request by akstuhl**
This PR adds documentation for the current Heroku/Git deployment process. It also adds a note clarifying development status of the Neatline for Omeka S project and updates the linked front-end app.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Looks good to me! Adding Makoto and @tezcatlipoca as reviewers to test this out.

**Comment by feralresearch** [comment]
This is awesome, yay documentation! Thank you.

**Comment by SteveMarvin** [comment]
Mine eyes hath beheld it. 👍

**Review by jamiefolsom — APPROVED** [review]
Looks good! 👍

**Pull request merged**
